# Generated by Django 6.0.1 on 2026-01-15 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('funding_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('funding_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('duration_years', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('upcoming', 'Upcoming')], default='open', max_length=20)),
                ('eligibility_criteria', models.TextField(blank=True)),
                ('application_url', models.URLField(blank=True)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('match_score', models.IntegerField(default=0, help_text='AI-calculated match score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_url', models.URLField(blank=True, help_text='URL from OurSG Grants Portal')),
                ('external_id', models.CharField(blank=True, help_text='External ID from source', max_length=100)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='grants.agency')),
            ],
            options={
                'ordering': ['-match_score', '-closing_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('focus_area', models.CharField(blank=True, max_length=200)),
                ('budget_required_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_required_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_years', models.CharField(blank=True, max_length=50)),
                ('kpis', models.TextField(blank=True, help_text='Key Performance Indicators')),
                ('service_outcomes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GrantMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(help_text='Match percentage (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('match_reasons', models.JSONField(default=list, help_text='List of reasons why this is a good match')),
                ('is_saved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.grant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.project')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.grant')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('organization_type', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('avatar_initials', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['status', 'closing_date'], name='grants_gran_status_fbd8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='grant',
            index=models.Index(fields=['match_score'], name='grants_gran_match_s_295b08_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grantmatch',
            unique_together={('project', 'grant')},
        ),
    ]
