# Generated by Django 6.0.1 on 2026-01-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='beneficiary_types',
            field=models.JSONField(default=list, help_text='List of beneficiary types (multi-select)'),
        ),
        migrations.AddField(
            model_name='project',
            name='interested_in',
            field=models.JSONField(default=list, help_text='List of interest areas (multi-select)'),
        ),
        migrations.AddField(
            model_name='project',
            name='need_support_for',
            field=models.JSONField(default=list, help_text='List of support types needed (multi-select)'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(blank=True, help_text='Project end date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(blank=True, help_text='Project start date', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_beneficiaries_count',
            field=models.IntegerField(blank=True, help_text='Target number of beneficiaries', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='want_support_from',
            field=models.JSONField(default=list, help_text='List of agencies to get support from (multi-select)'),
        ),
    ]
