# Generated by Django 6.0.1 on 2026-01-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_project_beneficiary_types_project_interested_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted (In Review)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
    ]
