# Generated by Django 6.0.1 on 2026-01-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='community_needs_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='description_of_project',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='last_saved',
            field=models.DateTimeField(blank=True, help_text='Last time proposal was saved', null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_evaluation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_publicity',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='project_uniqueness',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='proposal_title',
            field=models.CharField(blank=True, help_text='Editable proposal title', max_length=300),
        ),
    ]
