# Generated by Django 6.0.1 on 2026-01-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0004_application_community_needs_analysis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='grants.project'),
        ),
    ]
