# Generated by Django 6.0.1 on 2026-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_alter_application_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='funding_info',
            field=models.TextField(blank=True, help_text='Human readable funding information scraped from source'),
        ),
    ]
