# Generated by Django 6.0.1 on 2026-01-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0006_grant_funding_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='funding_info',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_auto_matching',
            field=models.BooleanField(default=True, help_text='Automatic grant matching'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_deadline_alerts',
            field=models.BooleanField(default=True, help_text='Smart deadline alerts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_proposal_assistance',
            field=models.BooleanField(default=True, help_text='AI proposal writing assistance'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ai_suggestions_enabled',
            field=models.BooleanField(default=True, help_text='AI-powered grant suggestions'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='funding_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='funding_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notification_threshold',
            field=models.CharField(choices=[('70', '70% - Good match'), ('80', '80% - High relevance only'), ('90', '90% - Excellent match only')], default='70', max_length=5),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_application_updates',
            field=models.BooleanField(default=True, help_text='Application status updates'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_deadline_reminders',
            field=models.BooleanField(default=True, help_text='Deadline reminder notifications'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True, help_text='Receive notifications via email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_new_grants',
            field=models.BooleanField(default=True, help_text='Notify on new matching grants'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notify_weekly_digest',
            field=models.BooleanField(default=False, help_text='Weekly digest of activities'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_registration',
            field=models.CharField(blank=True, help_text='Registration number', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_categories',
            field=models.JSONField(default=list, help_text='Preferred grant categories'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='typical_duration',
            field=models.CharField(choices=[('6_months', '6 months'), ('12_months', '12 months'), ('18_months', '18 months'), ('24_months', '24 months'), ('36_months', '36 months')], default='12_months', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('npo', 'Non-Profit Organization'), ('social_enterprise', 'Social Enterprise'), ('government', 'Government Agency'), ('academic', 'Academic Institution'), ('corporate', 'Corporate/Business'), ('individual', 'Individual')], max_length=50),
        ),
    ]
